// lib/screens/ai_buddy/ai_buddy_screen.dart

import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../core/constants/app_colors.dart';
import '../../core/constants/app_strings.dart';
import '../../core/constants/app_text_styles.dart';
import '../../providers/ai_provider.dart';
import '../../providers/habit_provider.dart';
import '../../providers/streak_provider.dart';

/// AI Habit Buddy screen — shows daily micro-goal and motivational pep talk.
/// Messages are generated by the Claude API based on the user's habit data.
class AiBuddyScreen extends StatefulWidget {
  const AiBuddyScreen({super.key});

  @override
  State<AiBuddyScreen> createState() => _AiBuddyScreenState();
}

class _AiBuddyScreenState extends State<AiBuddyScreen> {
  @override
  void initState() {
    super.initState();
    // Auto-fetch on screen open if no cached message
    WidgetsBinding.instance.addPostFrameCallback((_) => _fetchAll());
  }

  Future<void> _fetchAll() async {
    final aiProvider = context.read<AiProvider>();
    final habitProvider = context.read<HabitProvider>();
    final streakProvider = context.read<StreakProvider>();

    final habits = habitProvider.habits;
    if (habits.isEmpty) return;

    // Fetch micro-goal for the habit with the highest level
    final topHabit = habits.reduce(
      (a, b) => a.level > b.level ? a : b,
    );
    final streak = streakProvider.streakFor(topHabit.id);

    if (aiProvider.microGoal == null && streak != null) {
      await aiProvider.fetchMicroGoal(habit: topHabit, streak: streak);
    }

    // Fetch pep talk based on overall stats
    if (aiProvider.pepTalk == null) {
      await aiProvider.fetchPepTalk(
        habits: habits,
        totalStreakDays: streakProvider.topCurrentStreak,
        weeklyCompletionRate: 70, // TODO: compute from real data
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: AppColors.backgroundDark,
      appBar: AppBar(
        backgroundColor: AppColors.backgroundDark,
        title: Text(AppStrings.aiTitle, style: AppTextStyles.headingMedium),
        actions: [
          TextButton.icon(
            onPressed: () {
              context.read<AiProvider>().clearAll();
              _fetchAll();
            },
            icon: const Icon(Icons.refresh, color: AppColors.primary),
            label: Text(AppStrings.aiRefreshButton,
                style: const TextStyle(color: AppColors.primary)),
          ),
        ],
      ),
      body: Consumer<AiProvider>(
        builder: (context, aiProvider, _) {
          return SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // Robot mascot header
                _buildBuddyHeader(),
                const SizedBox(height: 24),

                // Micro-goal card
                Text(AppStrings.aiMicroGoalSection,
                    style: AppTextStyles.headingSmall),
                const SizedBox(height: 12),
                _buildMicroGoalCard(aiProvider),
                const SizedBox(height: 24),

                // Pep talk card
                Text(AppStrings.aiPepSection,
                    style: AppTextStyles.headingSmall),
                const SizedBox(height: 12),
                _buildPepTalkCard(aiProvider),

                const SizedBox(height: 32),
                _buildInsightPrompt(context),
              ],
            ),
          );
        },
      ),
    );
  }

  // Header
  Widget _buildBuddyHeader() {
    return Container(
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        gradient: LinearGradient(
          colors: [
            AppColors.primary.withOpacity(0.3),
            AppColors.accent.withOpacity(0.2),
          ],
        ),
        borderRadius: BorderRadius.circular(20),
      ),
      child: Row(
        children: [
          const Text('🤖', style: TextStyle(fontSize: 52)),
          const SizedBox(width: 16),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Text('Your AI Buddy', style: AppTextStyles.headingMedium),
                Text(
                  AppStrings.aiSubtitle,
                  style: AppTextStyles.bodySmall,
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // Micro-goal card
  Widget _buildMicroGoalCard(AiProvider provider) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppColors.backgroundCard,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: AppColors.primary.withOpacity(0.3),
          width: 1.5,
        ),
      ),
      child: provider.isLoadingGoal
          ? _buildLoading(AppStrings.aiLoadingGoal)
          : Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    const Text('🎯', style: TextStyle(fontSize: 20)),
                    const SizedBox(width: 8),
                    Text("Today's Focus",
                        style: AppTextStyles.labelMedium.copyWith(
                            color: AppColors.primary)),
                  ],
                ),
                const SizedBox(height: 12),
                Text(
                  provider.microGoal ?? AppStrings.aiFallback,
                  style: AppTextStyles.aiMicroGoal,
                ),
              ],
            ),
    );
  }

  // Pep talk card
  Widget _buildPepTalkCard(AiProvider provider) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(20),
      decoration: BoxDecoration(
        color: AppColors.backgroundCard,
        borderRadius: BorderRadius.circular(16),
        border: Border.all(
          color: AppColors.accent.withOpacity(0.3),
          width: 1.5,
        ),
      ),
      child: provider.isLoadingPep
          ? _buildLoading(AppStrings.aiLoadingPep)
          : Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Row(
                  children: [
                    const Text('💬', style: TextStyle(fontSize: 20)),
                    const SizedBox(width: 8),
                    Text('From Your Buddy',
                        style: AppTextStyles.labelMedium.copyWith(
                            color: AppColors.accent)),
                  ],
                ),
                const SizedBox(height: 12),
                Text(
                  provider.pepTalk ?? AppStrings.aiFallback,
                  style: AppTextStyles.aiBuddyMessage,
                ),
              ],
            ),
    );
  }

  Widget _buildLoading(String message) {
    return Row(
      children: [
        const SizedBox(
          width: 20,
          height: 20,
          child: CircularProgressIndicator(
              strokeWidth: 2, color: AppColors.primary),
        ),
        const SizedBox(width: 12),
        Text(message, style: AppTextStyles.bodySmall),
      ],
    );
  }

  Widget _buildInsightPrompt(BuildContext context) {
    return InkWell(
      onTap: () => Navigator.pushNamed(context, '/reflection'),
      borderRadius: BorderRadius.circular(12),
      child: Container(
        padding: const EdgeInsets.all(16),
        decoration: BoxDecoration(
          color: AppColors.success.withOpacity(0.1),
          borderRadius: BorderRadius.circular(12),
          border: Border.all(
              color: AppColors.success.withOpacity(0.3)),
        ),
        child: Row(
          children: [
            const Text('📊', style: TextStyle(fontSize: 24)),
            const SizedBox(width: 12),
            Expanded(
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text('Get Weekly AI Insight',
                      style: AppTextStyles.headingSmall),
                  Text('Complete a reflection to unlock deeper analysis.',
                      style: AppTextStyles.bodySmall),
                ],
              ),
            ),
            const Icon(Icons.chevron_right, color: AppColors.textSecondary),
          ],
        ),
      ),
    );
  }
}